### PR TITLE
Use GitHub Actions and `ttree` to build the site

### PR DESCRIPTION
**Pull request by davorg**

### CODE REVIEW

**Comment by leejo** [comment]
@davorg - merged but the build is failing: https://github.com/LondonPM/London-pm-website/actions/runs/12525987788

**Comment by davorg** [comment]
Fixed. I needed to change the Pages build source so it's build using GitHub Actions.

**Comment by leejo** [comment]
👍 i'll leave you to it 😄

**Comment by davorg** [comment]
It's building correctly, but the CSS and image links are broken because it's now being served from a subdirectory. It's pointless to fix that as we'd need to roll it back when we start using the real domain again. So I'll use my temporary subdomain for the time being.

**Comment by davorg** [comment]
Actually, it turns out I still own https://londonperl.com/. So that's where the site is for the time being.

**Pull request merged**
